### ISSUE TITLE
Please add HydroAnalysis

### ISSUE THREAD

**Issue by dalmo1991** [raoulcollenteur/Python-Hydrology-Tools#5]
Hello. Pls add my new package. I think it belongs to "Time Series (Analysis)"

MD entry:
|[HidroAnalysis](https://github.com/dalmo1991/HydroAnalysis)| Python package to calculate indices and metrics useful in the everyday job of a hydrologist. |

Thanks!

**Comment by raoulcollenteur** [comment]
Done!  Thanks @dalmo1991 for the suggestion.
